package com.mojtaba.folentra.desktop.search

object SampleDesktopSearchDataSource {
    fun records(): List<DesktopSearchRecord> = listOf(
        DesktopSearchRecord(
            id = "demo-search-salary",
            title = "Sample Payroll Deposit",
            amountMinor = 320_000,
            currencyCode = "USD",
            type = DesktopSearchTransactionType.Income,
            occurredAtMillis = 1_769_878_800_000L,
            category = "Income",
            notePreview = "Sample paycheck",
            tags = listOf("work", "recurring"),
            recurring = true,
        ),
        DesktopSearchRecord(
            id = "demo-search-rent",
            title = "Sample Apartment Rent",
            amountMinor = -145_000,
            currencyCode = "USD",
            type = DesktopSearchTransactionType.Expense,
            occurredAtMillis = 1_769_936_400_000L,
            category = "Housing",
            notePreview = "Monthly housing sample",
            tags = listOf("essential", "recurring"),
            recurring = true,
        ),
        DesktopSearchRecord(
            id = "demo-search-groceries-a",
            title = "Sample Neighborhood Market",
            amountMinor = -8_742,
            currencyCode = "USD",
            type = DesktopSearchTransactionType.Expense,
            occurredAtMillis = 1_770_055_200_000L,
            category = "Groceries",
            notePreview = "Weekly grocery sample",
            tags = listOf("essential"),
        ),
        DesktopSearchRecord(
            id = "demo-search-transit",
            title = "Sample Transit Pass",
            amountMinor = -9_600,
            currencyCode = "USD",
            type = DesktopSearchTransactionType.Expense,
            occurredAtMillis = 1_770_105_600_000L,
            category = "Transportation",
            notePreview = "Monthly pass sample",
            tags = listOf("essential", "recurring"),
            recurring = true,
        ),
        DesktopSearchRecord(
            id = "demo-search-coffee",
            title = "Sample Coffee Stop",
            amountMinor = -625,
            currencyCode = "USD",
            type = DesktopSearchTransactionType.Expense,
            occurredAtMillis = 1_770_217_200_000L,
            category = "Dining",
            notePreview = "Client catch-up sample",
            tags = listOf("work"),
        ),
        DesktopSearchRecord(
            id = "demo-search-utilities",
            title = "Sample Power Bill",
            amountMinor = -12_840,
            currencyCode = "USD",
            type = DesktopSearchTransactionType.Expense,
            occurredAtMillis = 1_770_321_600_000L,
            category = "Utilities",
            notePreview = "Electric bill sample",
            tags = listOf("essential", "recurring"),
            recurring = true,
        ),
        DesktopSearchRecord(
            id = "demo-search-freelance",
            title = "Sample Freelance Invoice",
            amountMinor = 48_000,
            currencyCode = "USD",
            type = DesktopSearchTransactionType.Income,
            occurredAtMillis = 1_770_739_200_000L,
            category = "Income",
            notePreview = "Local demo invoice",
            tags = listOf("work"),
        ),
        DesktopSearchRecord(
            id = "demo-search-concert",
            title = "Sample Riverside Show",
            amountMinor = -8_250,
            currencyCode = "USD",
            type = DesktopSearchTransactionType.Expense,
            occurredAtMillis = 1_772_229_600_000L,
            category = "Entertainment",
            notePreview = "Weekend event sample",
            tags = listOf("weekend"),
        ),
    )
}
